name: pull_request_created
on:
  push:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  component-tests:
    strategy:
      matrix:
        parallel: [6]
        index: [0, 1, 2, 3, 4, 5] # Add more indices as needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21
        env:
          CGO_ENABLED: 0
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Generate go test Slice
        id: test_split
        uses: hashicorp-forge/go-test-split-action@v1
        with:
          index: ${{ matrix.index }}
          total: ${{ matrix.parallel }}
          flags: "--tags=integration"
          packages: "./tests/..."
      - name: Run component tests
        run: |
          cd tests && go test --timeout=20m --tags=integration -run "${{ steps.test_split.outputs.run }}"